name: Building

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - name: Check out ${{ github.repository }}
        uses: actions/checkout@v3

      - name: Check out Devolutions/actions
        uses: actions/checkout@v3
        with:
          repository: Devolutions/actions
          ref: master
          token: ${{ secrets.DEVOLUTIONSBOT_TOKEN }}
          path: ./.github/workflows

      - name: Build application
        uses: ./.github/workflows/powershell-build

      - uses: actions/upload-artifact@v3
        with:
          name: SecretManagement.DevolutionsServer
          path: ./package/SecretManagement.DevolutionsServer
